### ISSUE TITLE
Some incorrect references

### ISSUE THREAD

**Issue by codename1995** [SHI-Labs/3D-Point-Cloud-Learning#2]
It is great to proofread the reference. Some incorrect references are as follows:

[94] MvCNN was published in ICCV'15 instead of CVPR'15.
[75] BPS was published in ICCV'19 instead of ICCV Workshop'19.

**Comment by codename1995** [comment]
In the second paragraph of section 3.2.2, the reference [5] seem to be a wrong citation. The reference of 3D ShapeNet should be:
Z. Wu, S. Song, A. Khosla, F. Yu, L. Zhang, X. Tang, and J. Xiao, “3D shapeNets: A deep representation for volumetric shapes,” in CVPR, 2015.

**Comment by alonewithyou** [comment]
Thank you for your reminder! The repo and the preprint have been updated.
